### ISSUE TITLE
Male english voices?

### ISSUE THREAD

**Issue by Tank-Missile** [Shadowsith/qpicospeaker#1]
I've been waiting years for a desktop text-to-speech application for linux, and so far this looks very promising! However, I can't seem to find any documentation on svox, such as how to install more voices.

**Comment by Shadowsith** [comment]
Thank you for your interest in this project!
Unfortunately it seems there are no male voices for the svox library at linux available. 
I have choosen svox/pico2wave as first text to speech engine because the voices are more human like as the robotic voices on espeak and it is easy to implement it in a program. 

I have plans to add more engines to QPicoSpeaker (e.g festival) but I first need to have a look at each one whether it is worth to implement them. 

If you know some good alternatives to svox please let me know.

**Comment by Tank-Missile** [comment]
As much as I am an advocate of open source software, non-robotic sounding open source text-to-speech software is nearly non-existent on linux from the research I've done. I've tested espeak and festival, but both were far from ideal. Mind you I'm not asking for professional grade text-to-speech as espeak and festival are provided for free. The best text-to-speech service that I personally recommend, or did recommend until recently is AcapelaBox. Unfortunately, background music plays along with the voices for non-account users now, and account users are limited to 300 characters or less unless you purchase more "credits". Since you plan on adding Google Translate TTS support, could also add AcapelaBox support? In any case, svox voices are miles ahead of espeak, and I actually have found male voices from further research. Check the voice demos [here](https://svoxmobilevoices.wordpress.com/demos/). I'm particularly eyeballing the Michael voice, which is downloadable from the android store I think? Not sure how hard it would be to retrieve a voice from an apk file and convert it to a usable format for linux.

**Comment by Shadowsith** [comment]
As I found out the company behind SVOX has stopped to develop android apps years ago. The original APK can be found at several download sites but it only has the information about the voices, not the voices itself (they had to be downloaded separately).   

As first I will add the google translate service to my program because the Voices are very well for a 'free' accessible service and it has one male and female voice for each language. AcapelaBox has the disadvantage of 'music' in the background of it's demo version and I also don't know how to access the webservice. From Google Translate it is well known. 

It seems that good accessible voices are very rare under linux. 
Windows has the advantage of system built-in voice packages but for all other good text to speech programs you need to pay too.
